### PR TITLE
include products related with event's taxon descendants

### PR DESCRIPTION
**Pull request by nando**
not only those related with that specific taxon

### CODE REVIEW

**Comment by nando** [comment]
this issue comes from this one: https://github.com/suryart/spree_active_sale/pull/13

**Comment by suryart** [comment]
@nando  Can you have a look at STI implementation I was talking about here: https://github.com/suryart/spree_active_sale/tree/sti-implementation

This will solve many issues with regards to self and descendants availability with less queries for navigation of store.

You can create an ActiveSale named: "Men"

Inside that ActiveSale "Men", you can create an another ActiveSale as descendant named: "Apparel", in which you can create active_sale_events(which can hold product/taxon for apparel of men as eventable). 

I am still not satisfied with looking into ancestors for checking a descendant to be live. Because a product in apparel active_sale_events can not be live when "Apparel" will be return true. And that will break the flow.

**Comment by nando** [comment]
For me the inheritance relation between sale and event is confusing. In my mind a sale is simply a way to keep related events together, for example, "Winter Season". In that mind set it makes no much sense to me to ask if this_sale.is_active?

On the other hand, I think that queries generated by my implementation are very similar to those generated by Spree while the user is browsing the taxonomy (when you visit a first-level taxon Spree shows you the products directly related with that taxon, but also those related with any of its descendants). In other words, the queries generated by someone visiting my event page are very similar to those generated by someone visiting a store category.

If you don't feel satisfied with the behaviour I need, and I don't see the point of this complex model, maybe what is happening is that we have different needs, what do you think?

**Comment by suryart** [comment]
Your code change in product decorator for "find_live_taxons" will break this method(.live?) for product object: https://github.com/suryart/spree_active_sale/blob/master/app/models/spree/product_decorator.rb#L10 Which is being used here to show the product only when it is available: https://github.com/suryart/spree_active_sale/blob/master/app/controllers/spree/products_controller_decorator.rb#L13

Please understand that, I have created and contributing to this extension not because of somebody's requirement. I am here to build a feature. Feature that's flexible and can be used by anybody for any sort of requirements.

New implementation solves both of us problems. There is no such major change. Just the model naming convention and the ability of sale inheritance, that's it. 

In new implementation, you can still create a sale: "Winter Sale", and can add events to it. Same as you can do now. There is absolutely no change in the flow. It's as same as the current admin flow. It's just that, in new implementation. You will have ability to check if "Winter Sale" is live and active or not by one query, which is not possible in existing system. Let's say, you will want to show "Winter Sale" on your store only when there is any event(s) available in it. How will you do that? for that every time you'll check if there is any event(s) live and active?

For example: 

```
sale = Spree::ActiveSale.create(:name => "Winter Sale")
event = sale.active_sale_events.create(:name => "Lather jackets", :start_date => Time.now, :end_date => Time.now+7.days )
you can add more event based on different start and end date....
```

In current implementation if you need to check if winter sale has any live and active events in it:
   !sale.active_sale_events.select{|event| event.live_active? }.blank? # => true

In STI(new) implementation I am proposing:
   sale.live_active? # => true

IMO the second is much cleaner. Every time you'll check for a sale's(a group of events) availability, the first implementation will ask for events and then show the result. But, second will just look into the sale's start and end date with is_active? attribute(absolutely no db query). 

I didn't change anything in test cases. And all specs are passing, i.e. there is absolutely no change in the current flow, just added the flexibility for sales and events. Check here: https://travis-ci.org/suryart/spree_active_sale/builds/6272857

Can you just try sti-implementation branch? There is no change in admin and events flow. After switching to the branch. You'll need new migrations, so just run rails g spree_active_sale:install. It should do the heavy lifting without breaking anything for you.

Let me know what you think?

**Comment by nando** [comment]
Nice to know your motivations. My case is different, i'm contributing to make it fix with very specific requirements. In this particular case, yesterday due to new requirements we've finally decided to create dedicated leaf taxons for each event, so my change is no longer needed for us.

But in a previous project I've been we had a very deep taxonomy with lots of internal (not-leaf) taxons (wines origin classification). Products (wines) are related with the leaf taxons (wineries). What should the admin user do in this situation? Should she/he create as many events as leaf taxons (wineries) on the desired branch (for example, the region of Bourdeaux)? If that's the case, that'd be a pain.

Yes, of course, with our current needs the sti-branch fits nice, I'll try it.

Thanks Surya!

**Comment by nando** [comment]
Suryart, we're currently using your master branch with the sti implementation and it seems to work nice so far.

Thanks!

**Comment by suryart** [comment]
I am glad to hear that. And, you're most welcome!

**Pull request closed without merging**
