### PR TITLE
event discount percentage

### PR DESCRIPTION
**Pull request by nando**
no logic, just to show it at views (if needed)

### CODE REVIEW

**Comment by suryart** [comment]
I was about to work on this, great you've initiated this. I'll look into the logic now.

**Comment by nando** [comment]
we need no any logic related with this field, for us it's just a fancy claim. so for us it would be nice if the impact on the business logic could be activated through a preference.

**Comment by suryart** [comment]
So, according to you. You're going to calculate the discounted price by yourself and then put it in product's price column? That will confuse the admin with related to discounting, as admin will not know if this is just a fancy thing to show and will not do actual discounting?

**Comment by nando** [comment]
For us it's just a label (it's our client/future-admin requirement), but of course it could and should be used for something more (that's why I've created as an integer, and not as a string).

**Pull request merged**
